openapi: 3.0.3
info:
  version: 0.1.0
  title: Hiarc API
  license:
    name: MIT
  description: |-
    Welcome to the Hiarc API documentation.
servers:
  - description: HiarcServer
    url: 'http://localhost:5000'
security:
  - AdminApiKeyAuth: []
  - JWTBearerAuth: []
paths:
  '/users':
    post:
      summary: Create a User
      security:
        - AdminApiKeyAuth: []
      operationId: createUser
      tags:
        - User
      requestBody:
        description: 'User information'
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUser"
      responses:
        '201':
          description: A User object
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/User"
  '/users/{key}':
    get:
      summary: Get a User
      security:
        - AdminApiKeyAuth: []
      operationId: getUser
      tags:
        - User
      parameters:
        - name: key
          in: path
          required: true
          description: 'Key of user to get'
          schema:
            type: string 
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/User"
  '/files':
    post:
      summary: Create a File
      security:
        - AdminApiKeyAuth: []
        - JWTBearerAuth: []
      operationId: createFile
      tags:
        - File
      parameters:
        - in: header
          name: X-Hiarc-User-Key
          schema:
            type: string
      requestBody:
        description: 'File information'
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/CreateFile"
      responses:
        '201':
          description: A File object
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/File"
  '/files/{key}/download':
    get:
      summary: Download a File
      security:
        - AdminApiKeyAuth: []
        - JWTBearerAuth: []
      operationId: downloadFile
      tags:
        - File
      parameters:
        - name: X-Hiarc-User-Key
          in: header
          description: 'Optional key of user to impersonate'
          schema:
            type: string
        - name: key
          in: path
          required: true
          description: 'Key of file to download'
          schema:
            type: string 
      responses:
        '200':
          description: A binary file
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
components:
  schemas:
    EntityBase:
      required:
        - key
      properties:
        key:
          type: string
        name:
          type: string
        description:
          type: string
        metadata:
          type: object
    EntityResponseBase:
      allOf:
        - $ref: '#/components/schemas/EntityBase'
        - type: object
          properties:
            type:
              type: string
            createdBy:
              type: string
            createdAt:
              type: string
              format: date-time
            modifiedAt:
              type: string
              format: date-time
    CreateUser:
      allOf:
        - $ref: '#/components/schemas/EntityBase'
    CreateFile:
      type: object
      properties:
        request:
          allOf:
            - $ref: '#/components/schemas/EntityBase'
            - type: object
              properties:
                StorageService:
                  type: string
        file:
          type: string
          format: binary
    User:
      allOf:
        - $ref: '#/components/schemas/EntityResponseBase'
    File:
      allOf:
        - $ref: '#/components/schemas/EntityResponseBase'
        - type: object
          properties:
            versionCount:
              type: number
  securitySchemes:
    AdminApiKeyAuth:
      type: apiKey
      in: header
      name: X-Hiarc-Api-Key
    JWTBearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT